name: Writerside Build
description: "Build Writerside documentation."
inputs:
  instance:
    description: "Instance name."
    required: true
  directory:
    description: "Directory containing the Writerside project."
    required: false
    default: "doc"
  deploy:
    description: "Deploy to GitHub Pages or not."
    required: false
    default: ""
  docker-version:
    description: "Docker version to use."
    required: false
    default: "243.22562"
  artifact-name:
    description: "Artifact name to use."
    required: false
    default: "docs"
  version:
    description: "Version number to use."
    required: false
    default: ""
  version-to-replace:
    description: "Version number in the writerside.cfg file to replace."
    required: false
    default: "main"

runs:
  using: composite

  steps:
    - name: Define Variables
      shell: bash
      run: |
        INSTANCE=${{ inputs.instance }}
        echo "ARTIFACT=webHelp${INSTANCE@U}2-all.zip" >> "${GITHUB_ENV}"

    - name: Set Version
      if: ${{ inputs.version }}
      uses: richardrigutins/replace-in-files@v2
      with:
        files: ${{ inputs.directory }}/writerside.cfg
        search-text: 'version="main"'
        replacement-text: 'version="${{ inputs.version }}"'

    - name: Build Documentation
      uses: JetBrains/writerside-github-action@v4
      with:
        instance: ${{ inputs.directory }}/${{ inputs.instance }}
        artifact: ${{ env.ARTIFACT }}
        docker-version: ${{ inputs.docker-version }}

    - name: Save Documentation As Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: |
          artifacts/webHelpMRKWATKINS.AST2-all.zip
          artifacts/report.json
        retention-days: 7

    - name: Unzip Documentation
      if: ${{ inputs.deploy }}
      shell: bash
      run: unzip -O UTF-8 -qq artifacts/${{ env.ARTIFACT }} -d pages-temp

    - name: Setup Pages
      if: ${{ inputs.deploy }}
      uses: actions/configure-pages@v5

    - name: Upload Documentation
      if: ${{ inputs.deploy }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: pages-temp

    - name: Deploy to GitHub Pages
      if: ${{ inputs.deploy }}
      uses: actions/deploy-pages@v4